function T = getTMat(theta,theta2,theta3,theta4,theta5)
theta = theta*pi/180;
theta2 = theta2*pi/180;
theta3 = theta3*pi/180;
theta4 = theta4*pi/180;
theta5 = theta5*pi/180;

T = [sin(theta5)*sin(theta)-cos(theta2)*cos(theta3)*cos(theta4)*cos(theta5)*cos(theta) + cos(theta2)*cos(theta5)*cos(theta)*sin(theta3)*sin(theta4)+cos(theta3)*cos(theta5)*cos(theta)*sin(theta2)*sin(theta4)+cos(theta4)*cos(theta5)*cos(theta)*sin(theta2)*sin(theta3) cos(theta5)*sin(theta)+cos(theta2)*cos(theta3)*cos(theta4)*cos(theta)*sin(theta5)-cos(theta2)*cos(theta)*sin(theta3)*sin(theta4)*sin(theta5)-cos(theta3)*cos(theta)*sin(theta2)*sin(theta4)*sin(theta5)-cos(theta4)*cos(theta)*sin(theta2)*sin(theta3)*sin(theta5)  sin(theta2 + theta3 + theta4 - theta)/2+sin(theta2 + theta3 + theta4 + theta)/2 2*cos(theta)*(36*sin(theta2 + theta3 + theta4)+80*sin(theta2 + theta3)+125*sin(theta2));
 cos(theta2)*cos(theta5)*sin(theta3)*sin(theta4)*sin(theta)-cos(theta2)*cos(theta3)*cos(theta4)*cos(theta5)*sin(theta) - cos(theta)*sin(theta5)+cos(theta3)*cos(theta5)*sin(theta2)*sin(theta4)*sin(theta) + cos(theta4)*cos(theta5)*sin(theta2)*sin(theta3)*sin(theta) cos(theta2)*cos(theta3)*cos(theta4)*sin(theta5)*sin(theta) - cos(theta5)*cos(theta) - cos(theta2)*sin(theta3)*sin(theta4)*sin(theta5)*sin(theta)-cos(theta3)*sin(theta2)*sin(theta4)*sin(theta5)*sin(theta)-cos(theta4)*sin(theta2)*sin(theta3)*sin(theta5)*sin(theta) cos(theta2 + theta3 + theta4 - theta)/2-cos(theta2 + theta3 + theta4 + theta)/2 2*sin(theta)*(36*sin(theta2 + theta3 + theta4)+80*sin(theta2 + theta3)+125*sin(theta2));
                                                                                                                                                                                        sin(theta2 + theta3 + theta4 - theta5)/2 + sin(theta2 + theta3 + theta4 + theta5)/2,                                                                                                                                                                                        cos(theta2 + theta3 + theta4 + theta5)/2 - cos(theta2 + theta3 + theta4 - theta5)/2,                                                     cos(theta2 + theta3 + theta4),         72*cos(theta2 + theta3 + theta4) + 160*cos(theta2 + theta3) + 250*cos(theta2) + 300;
                                                                                                                                                                                                                                                            0,                                                                                                                                                                                                                                                                          0,                                                                                 0,                                                                                           1];
end
                                                                                                                                                                                                                                                     